title: Escritos
description: Escritos do Alexandre Costa

url: http://alexandre786.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Início
   url: /index.html
 - title: Sobre
   url: /about
 - title: Contato
   url: /contato

social:
   github: alexandre786
   twitter: alexandre786
   facebook: alexandre.psi
   email: alexandre.psi@gmail.com

google_analytics: ""
