# Site settings
title: 'Alexandre Costa' # Your Title
tagline: 'Artigos sobre os mais variados assuntos' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: # the subpath of your site, e.g. /blog/
twitter_username: alexandre786
github_username:  alexandre786